// <auto-generated />
using System;
using GroceryInventoryTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryInventoryTracker.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroceryInventoryTracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Produce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dry Goods"
                        });
                });

            modelBuilder.Entity("GroceryInventoryTracker.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImagePath = "https://images.unsplash.com/photo-1560806e614-56f27138e5de?w=400&h=400&fit=crop",
                            Name = "Apples"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImagePath = "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop",
                            Name = "Bananas"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ImagePath = "https://images.unsplash.com/photo-1550583724-b2692b25a968?w=400&h=400&fit=crop",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            ImagePath = "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ImagePath = "https://images.unsplash.com/photo-1585590954945-f8e1ef4f1f4e?w=400&h=400&fit=crop",
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            ImagePath = "https://images.unsplash.com/photo-1586190936819-754668823f66?w=400&h=400&fit=crop",
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            ImagePath = "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=400&fit=crop",
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            ImagePath = "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=400&fit=crop",
                            Name = "Pasta"
                        });
                });

            modelBuilder.Entity("GroceryInventoryTracker.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasDefaultValue("InStorage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpirationDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 25,
                            Location = "InStorage",
                            ShipmentNumber = "1001"
                        },
                        new
                        {
                            Id = 2,
                            ExpirationDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 60,
                            Location = "OnFloor",
                            ShipmentNumber = "1002"
                        },
                        new
                        {
                            Id = 3,
                            ExpirationDate = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 50,
                            Location = "InStorage",
                            ShipmentNumber = "2001"
                        },
                        new
                        {
                            Id = 4,
                            ExpirationDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 70,
                            Location = "OnFloor",
                            ShipmentNumber = "2002"
                        },
                        new
                        {
                            Id = 5,
                            ExpirationDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 40,
                            Location = "InStorage",
                            ShipmentNumber = "3001"
                        },
                        new
                        {
                            Id = 6,
                            ExpirationDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 40,
                            Location = "OnFloor",
                            ShipmentNumber = "3002"
                        },
                        new
                        {
                            Id = 7,
                            ExpirationDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 20,
                            Location = "InStorage",
                            ShipmentNumber = "4001"
                        },
                        new
                        {
                            Id = 8,
                            ExpirationDate = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 30,
                            Location = "OnFloor",
                            ShipmentNumber = "4002"
                        },
                        new
                        {
                            Id = 9,
                            ExpirationDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Quantity = 100,
                            Location = "InStorage",
                            ShipmentNumber = "5001"
                        },
                        new
                        {
                            Id = 10,
                            ExpirationDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Quantity = 100,
                            Location = "OnFloor",
                            ShipmentNumber = "5002"
                        },
                        new
                        {
                            Id = 11,
                            ExpirationDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Quantity = 50,
                            Location = "InStorage",
                            ShipmentNumber = "6001"
                        },
                        new
                        {
                            Id = 12,
                            ExpirationDate = new DateTime(2027, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Quantity = 50,
                            Location = "OnFloor",
                            ShipmentNumber = "6002"
                        },
                        new
                        {
                            Id = 13,
                            ExpirationDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Quantity = 40,
                            Location = "InStorage",
                            ShipmentNumber = "7001"
                        },
                        new
                        {
                            Id = 14,
                            ExpirationDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Quantity = 35,
                            Location = "OnFloor",
                            ShipmentNumber = "7002"
                        },
                        new
                        {
                            Id = 15,
                            ExpirationDate = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            Quantity = 50,
                            Location = "InStorage",
                            ShipmentNumber = "8001"
                        },
                        new
                        {
                            Id = 16,
                            ExpirationDate = new DateTime(2027, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            Quantity = 40,
                            Location = "OnFloor",
                            ShipmentNumber = "8002"
                        });
                });

            modelBuilder.Entity("GroceryInventoryTracker.Models.Product", b =>
                {
                    b.HasOne("GroceryInventoryTracker.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GroceryInventoryTracker.Models.Shipment", b =>
                {
                    b.HasOne("GroceryInventoryTracker.Models.Product", "Product")
                        .WithMany("Shipments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GroceryInventoryTracker.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GroceryInventoryTracker.Models.Product", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
